In [1]:
%load_ext sql
%sql postgresql://postgres:1234@localhost:5432/postgres

In [2]:
# %config SqlMagic.autocommit=False

In [6]:
%%sql

DROP TABLE IF EXISTS name_gender;
CREATE TABLE name_gender (
    name varchar(32),
    gender varchar(16)
);
INSERT INTO name_gender VALUES ('Ben','MALE'),('Maddie','FEMALE');

%%sql
DELETE FROM name_gender;
SELECT *
FROM name_gender;
COMMIT;

In [8]:
%%sql

SELECT * FROM name_gender;

In [4]:
%%sql
SET search_path to cleantable

 * postgresql://postgres:***@localhost:5432/postgres
Done.

[]

In [80]:
%%sql
select RANK(1000000000000000) WITHIN GROUP(ORDER BY price) "RANK" from item_data
group by category;

 * postgresql://postgres:***@localhost:5432/postgres
11 rows affected.

[(65,),
 (61,),
 (363,),
 (184,),
 (153,),
 (115,),
 (57,),
 (260,),
 (246,),
 (310,),
 (239,)]

In [83]:
%%sql
select * from item_data;

 * postgresql://postgres:***@localhost:5432/postgres
2042 rows affected.

[(200000, 'beauty', 79900),
 (200001, 'kitchen', 99000),
 (200002, 'food', 49900),
 (200008, 'stuff', 49800),
 (200009, 'stuff', 49800),
 (200013, 'food', 39900),
 (200014, 'food', 55900),
 (200017, 'food', 49900),
 (200018, 'food', 49900),
 (200023, 'food', 49900),
 (200024, 'food', 29900),
 (200025, 'food', 39900),
 (200026, 'food', 49900),
 (200027, 'stuff', 39000),
 (200028, 'stuff', 29000),
 (200029, 'stuff', 29000),
 (200030, 'stuff', 39000),
 (200031, 'stuff', 29000),
 (200032, 'stuff', 29000),
 (200033, 'food', 69900),
 (200034, 'food', 49900),
 (200035, 'daily_supplies', 99800),
 (200036, 'daily_supplies', 64800),
 (200037, 'daily_supplies', 61800),
 (200038, 'food', 43900),
 (200039, 'food', 40900),
 (200040, 'food', 49900),
 (200041, 'kitchen', 109000),
 (200042, 'kitchen', 99000),
 (200043, 'daily_supplies', 119000),
 (200046, 'stuff', 199000),
 (200047, 'stuff', 99000),
 (200048, 'stuff', 139000),
 (200049, 'stuff', 299000),
 (200050, 'stuff', 399000),
 (200051, 'stuff', 1199000),
 (200052, 'stuff', 1690000),
 (200053, 'stuff', 599000),
 (200054, 'stuff', 69000),
 (200055, 'stuff', 69000),
 (200056, 'stuff', 54900),
 (200061, 'stuff', 458000),
 (200062, 'stuff', 458000),
 (200065, 'stuff', 690000),
 (200068, 'stuff', 380000),
 (200069, 'stuff', 2730000),
 (200070, 'stuff', 2590000),
 (200071, 'stuff', 1480000),
 (200073, 'stuff', 880000),
 (200075, 'stuff', 790000),
 (200076, 'stuff', 790000),
 (200077, 'stuff', 790000),
 (200078, 'stuff', 348000),
 (200080, 'stuff', 1590000),
 (200081, 'stuff', 1590000),
 (200082, 'stuff', 1690000),
 (200084, 'stuff', 1620000),
 (200085, 'stuff', 1620000),
 (200086, 'stuff', 1620000),
 (200087, 'stuff', 1590000),
 (200088, 'stuff', 1590000),
 (200089, 'stuff', 1580000),
 (200090, 'stuff', 1580000),
 (200091, 'stuff', 1790000),
 (200093, 'stuff', 790000),
 (200094, 'stuff', 1290000),
 (200095, 'stuff', 1190000),
 (200097, 'stuff', 1380000),
 (200098, 'stuff', 1150000),
 (200100, 'stuff', 1280000),
 (200101, 'stuff', 1280000),
 (200102, 'stuff', 1280000),
 (200103, 'stuff', 1590000),
 (200104, 'stuff', 790000),
 (200105, 'stuff', 790000),
 (200106, 'stuff', 790000),
 (200107, 'stuff', 790000),
 (200108, 'stuff', 1180000),
 (200109, 'stuff', 1350000),
 (200110, 'stuff', 248000),
 (200111, 'stuff', 248000),
 (200112, 'stuff', 1090000),
 (200113, 'stuff', 1590000),
 (200114, 'food', 39900),
 (200115, 'cloth', 39800),
 (200116, 'cloth', 49800),
 (200117, 'cloth', 59800),
 (200118, 'cloth', 29900),
 (200119, 'cloth', 39900),
 (200120, 'cloth', 29900),
 (200121, 'cloth', 29900),
 (200122, 'health', 99000),
 (200123, 'beauty', 69900),
 (200125, 'food', 30900),
 (200126, 'food', 30900),
 (200127, 'daily_supplies', 49000),
 (200128, 'daily_supplies', 127000),
 (200129, 'daily_supplies', 88000),
 (200130, 'daily_supplies', 329000),
 (200131, 'daily_supplies', 304000),
 (200132, 'cloth', 399000),
 (200133, 'food', 109900),
 (200134, 'daily_supplies', 89800),
 (200135, 'daily_supplies', 59800),
 (200136, 'food', 40900),
 (200137, 'health', 189000),
 (200138, 'health', 179000),
 (200139, 'health', 59000),
 (200140, 'health', 149000),
 (200141, 'health', 139000),
 (200142, 'health', 69000),
 (200144, 'health', 79000),
 (200145, 'health', 159000),
 (200148, 'kitchen', 64900),
 (200149, 'kitchen', 54800),
 (200150, 'kitchen', 50800),
 (200151, 'cloth', 149000),
 (200152, 'cloth', 149000),
 (200153, 'cloth', 690000),
 (200154, 'kitchen', 76000),
 (200155, 'kitchen', 99000),
 (200156, 'kitchen', 94800),
 (200157, 'kitchen', 89800),
 (200158, 'kitchen', 69000),
 (200159, 'kitchen', 94000),
 (200160, 'kitchen', 88800),
 (200161, 'home_appliance', 539000),
 (200162, 'home_appliance', 539000),
 (200163, 'home_appliance', 539000),
 (200164, 'home_appliance', 539000),
 (200165, 'home_appliance', 749000),
 (200166, 'home_appliance', 749000),
 (200167, 'home_appliance', 749000),
 (200168, 'home_appliance', 749000),
 (200169, 'home_appliance', 509000),
 (200170, 'home_appliance', 509000),
 (200171, 'home_appliance', 509000),
 (200172, 'home_appliance', 509000),
 (200173, 'home_appliance', 709000),
 (200174, 'home_appliance', 709000),
 (200175, 'home_appliance', 709000),
 (200176, 'home_appliance', 709000),
 (200189, 'stuff', 59000),
 (200190, 'stuff', 59000),
 (200191, 'stuff', 39900),
 (200197, 'beauty', 39800),
 (200199, 'beauty', 39800),
 (200200, 'beauty', 39800),
 (200201, 'beauty', 39800),
 (200202, 'beauty', 39800),
 (200203, 'furniture', 399000),
 (200204, 'furniture', 1190000),
 (200205, 'furniture', 1390000),
 (200206, 'furniture', 299000),
 (200207, 'furniture', 599000),
 (200208, 'furniture', 2980000),
 (200209, 'furniture', 2682000),
 (200210, 'furniture', 3150000),
 (200211, 'furniture', 2835000),
 (200213, 'underwear', 49900),
 (200215, 'underwear', 99900),
 (200218, 'underwear', 79900),
 (200219, 'underwear', 89900),
 (200220, 'underwear', 89900),
 (200223, 'cloth', 69900),
 (200224, 'stuff', 318000),
 (200225, 'stuff', 398000),
 (200226, 'stuff', 438000),
 (200227, 'stuff', 428000),
 (200228, 'stuff', 280000),
 (200229, 'stuff', 336000),
 (200230, 'stuff', 224000),
 (200231, 'kitchen', 99000),
 (200232, 'kitchen', 99000),
 (200233, 'kitchen', 50900),
 (200234, 'kitchen', 30900),
 (200235, 'kitchen', 50900),
 (200236, 'kitchen', 60900),
 (200237, 'kitchen', 60900),
 (200238, 'kitchen', 60900),
 (200239, 'kitchen', 94000),
 (200240, 'cloth', 59000),
 (200241, 'cloth', 59000),
 (200242, 'cloth', 59000),
 (200243, 'cloth', 49000),
 (200244, 'cloth', 59000),
 (200245, 'cloth', 59000),
 (200246, 'cloth', 59000),
 (200247, 'cloth', 49000),
 (200248, 'home_appliance', 899000),
 (200249, 'home_appliance', 899000),
 (200250, 'home_appliance', 2549000),
 (200252, 'home_appliance', 899000),
 (200253, 'home_appliance', 2599000),
 (200254, 'cloth', 79000),
 (200255, 'cloth', 59900),
 (200256, 'cloth', 69000),
 (200257, 'cloth', 109000),
 (200258, 'cloth', 89000),
 (200259, 'kitchen', 109000),
 (200260, 'kitchen', 139000),
 (200261, 'kitchen', 129000),
 (200262, 'kitchen', 104000),
 (200263, 'kitchen', 129000),
 (200264, 'kitchen', 119000),
 (200265, 'kitchen', 129000),
 (200267, 'kitchen', 109000),
 (200268, 'kitchen', 129000),
 (200269, 'kitchen', 119000),
 (200271, 'underwear', 119000),
 (200275, 'underwear', 119000),
 (200276, 'underwear', 119000),
 (200277, 'underwear', 119000),
 (200278, 'underwear', 119000),
 (200279, 'kitchen', 64800),
 (200281, 'kitchen', 98000),
 (200282, 'kitchen', 69800),
 (200283, 'kitchen', 119000),
 (200284, 'kitchen', 93000),
 (200285, 'kitchen', 64800),
 (200286, 'kitchen', 109000),
 (200287, 'kitchen', 69000),
 (200288, 'kitchen', 61800),
 (200298, 'cloth', 139000),
 (200301, 'cloth', 139000),
 (200302, 'cloth', 29800),
 (200303, 'cloth', 39800),
 (200305, 'bedding', 49900),
 (200306, 'bedding', 69900),
 (200307, 'bedding', 59900),
 (200308, 'bedding', 59900),
 (200309, 'bedding', 49900),
 (200310, 'bedding', 69900),
 (200311, 'kitchen', 259000),
 (200312, 'kitchen', 239000),
 (200313, 'food', 42900),
 (200314, 'daily_supplies', 108000),
 (200315, 'daily_supplies', 100000),
 (200318, 'kitchen', 74800),
 (200319, 'beauty', 69900),
 (200320, 'beauty', 69900),
 (200332, 'underwear', 50900),
 (200333, 'health', 77000),
 (200334, 'health', 79000),
 (200335, 'daily_supplies', 159000),
 (200336, 'cloth', 69900),
 (200337, 'cloth', 89000),
 (200338, 'cloth', 89000),
 (200339, 'cloth', 77000),
 (200340, 'cloth', 99000),
 (200341, 'cloth', 69900),
 (200342, 'cloth', 79900),
 (200343, 'cloth', 59900),
 (200344, 'cloth', 69900),
 (200345, 'cloth', 59900),
 (200346, 'cloth', 59900),
 (200347, 'cloth', 89000),
 (200348, 'cloth', 89000),
 (200349, 'cloth', 66000),
 (200350, 'cloth', 59900),
 (200351, 'cloth', 99000),
 (200352, 'cloth', 69900),
 (200353, 'cloth', 69900),
 (200354, 'cloth', 59900),
 (200355, 'cloth', 69900),
 (200356, 'cloth', 59900),
 (200359, 'daily_supplies', 59000),
 (200360, 'daily_supplies', 99000),
 (200361, 'daily_supplies', 39900),
 (200362, 'daily_supplies', 19900),
 (200363, 'daily_supplies', 79000),
 (200364, 'daily_supplies', 158000),
 (200365, 'daily_supplies', 39000),
 (200366, 'daily_supplies', 98000),
 (200367, 'daily_supplies', 98000),
 (200371, 'daily_supplies', 59000),
 (200372, 'bedding', 69900),
 (200373, 'bedding', 59900),
 (200374, 'bedding', 49900),
 (200375, 'bedding', 79900),
 (200376, 'bedding', 69900),
 (200377, 'bedding', 59900),
 (200382, 'bedding', 59900),
 (200383, 'bedding', 69900),
 (200384, 'bedding', 49900),
 (200385, 'bedding', 59900),
 (200386, 'bedding', 69900),
 (200387, 'bedding', 79900),
 (200388, 'bedding', 39900),
 (200389, 'bedding', 49900),
 (200390, 'bedding', 79900),
 (200391, 'bedding', 69900),
 (200392, 'bedding', 89900),
 (200393, 'bedding', 59900),
 (200394, 'bedding', 79900),
 (200395, 'bedding', 69900),
 (200396, 'bedding', 89900),
 (200397, 'bedding', 59900),
 (200398, 'bedding', 69900),
 (200399, 'bedding', 59900),
 (200400, 'bedding', 79900),
 (200401, 'bedding', 49900),
 (200402, 'bedding', 79900),
 (200403, 'bedding', 69900),
 (200404, 'bedding', 89900),
 (200405, 'bedding', 59900),
 (200406, 'daily_supplies', 1980000),
 (200407, 'daily_supplies', 1800000),
 (200408, 'daily_supplies', 49900),
 (200409, 'daily_supplies', 99900),
 (200410, 'home_appliance', 2990000),
 (200411, 'home_appliance', 1200000),
 (200412, 'home_appliance', 1700000),
 (200413, 'home_appliance', 2840000),
 (200423, 'home_appliance', 1899000),
 (200427, 'home_appliance', 489000),
 (200428, 'home_appliance', 1649000),
 (200429, 'home_appliance', 1420000),
 (200430, 'home_appliance', 1440000),
 (200431, 'home_appliance', 1330000),
 (200432, 'home_appliance', 1440000),
 (200433, 'home_appliance', 1440000),
 (200434, 'home_appliance', 1430000),
 (200435, 'home_appliance', 1330000),
 (200436, 'home_appliance', 1330000),
 (200437, 'home_appliance', 1330000),
 (200438, 'home_appliance', 1250000),
 (200439, 'home_appliance', 2130000),
 (200440, 'home_appliance', 1920000),
 (200441, 'home_appliance', 2130000),
 (200442, 'home_appliance', 2130000),
 (200443, 'home_appliance', 1930000),
 (200444, 'home_appliance', 1920000),
 (200445, 'home_appliance', 1920000),
 (200446, 'home_appliance', 1920000),
 (200447, 'home_appliance', 1800000),
 (200448, 'home_appliance', 2990000),
 (200449, 'home_appliance', 2990000),
 (200450, 'home_appliance', 2690000),
 (200451, 'home_appliance', 2990000),
 (200452, 'home_appliance', 2790000),
 (200453, 'home_appliance', 2690000),
 (200454, 'home_appliance', 2690000),
 (200455, 'home_appliance', 2690000),
 (200456, 'home_appliance', 3090000),
 (200457, 'home_appliance', 2990000),
 (200458, 'home_appliance', 3190000),
 (200459, 'home_appliance', 3190000),
 (200460, 'home_appliance', 2990000),
 (200461, 'home_appliance', 899000),
 (200462, 'home_appliance', 999000),
 (200463, 'home_appliance', 1089000),
 (200464, 'home_appliance', 489000),
 (200465, 'home_appliance', 489000),
 (200466, 'home_appliance', 899000),
 (200467, 'home_appliance', 1149000),
 (200468, 'home_appliance', 2549000),
 (200469, 'home_appliance', 2549000),
 (200470, 'home_appliance', 2299000),
 (200471, 'home_appliance', 2299000),
 (200472, 'home_appliance', 2299000),
 (200473, 'home_appliance', 1989000),
 (200474, 'home_appliance', 1989000),
 (200475, 'home_appliance', 1989000),
 (200476, 'home_appliance', 2139000),
 (200477, 'home_appliance', 2139000),
 (200478, 'home_appliance', 1989000),
 (200479, 'home_appliance', 2299000),
 (200480, 'home_appliance', 1440000),
 (200481, 'home_appliance', 1890000),
 (200482, 'home_appliance', 2049000),
 (200483, 'home_appliance', 443000),
 (200485, 'home_appliance', 1499000),
 (200487, 'home_appliance', 1549000),
 (200488, 'home_appliance', 1549000),
 (200489, 'home_appliance', 1499000),
 (200490, 'home_appliance', 1239000),
 (200491, 'home_appliance', 319000),
 (200492, 'home_appliance', 1890000),
 (200493, 'home_appliance', 1790000),
 (200494, 'home_appliance', 1990000),
 (200495, 'home_appliance', 1559000),
 (200496, 'home_appliance', 1330000),
 (200497, 'home_appliance', 1300000),
 (200498, 'home_appliance', 1200000),
 (200499, 'home_appliance', 1300000),
 (200500, 'home_appliance', 1300000),
 (200501, 'home_appliance', 1300000),
 (200502, 'home_appliance', 1200000),
 (200503, 'home_appliance', 1200000),
 (200504, 'home_appliance', 1200000),
 (200505, 'home_appliance', 1200000),
 (200506, 'home_appliance', 1900000),
 (200507, 'home_appliance', 1690000),
 (200508, 'home_appliance', 1900000),
 (200509, 'home_appliance', 1900000),
 (200510, 'home_appliance', 1700000),
 (200511, 'home_appliance', 1690000),
 (200512, 'home_appliance', 1690000),
 (200513, 'home_appliance', 1690000),
 (200514, 'home_appliance', 1750000),
 (200515, 'home_appliance', 2700000),
 (200516, 'home_appliance', 2700000),
 (200517, 'home_appliance', 2400000),
 (200518, 'home_appliance', 2700000),
 (200519, 'home_appliance', 2500000),
 (200520, 'home_appliance', 2400000),
 (200521, 'home_appliance', 2400000),
 (200522, 'home_appliance', 2400000),
 (200523, 'home_appliance', 2700000),
 (200524, 'home_appliance', 2800000),
 (200525, 'home_appliance', 2700000),
 (200526, 'home_appliance', 2900000),
 (200527, 'home_appliance', 2900000),
 (200528, 'home_appliance', 2750000),
 (200529, 'home_appliance', 829000),
 (200530, 'home_appliance', 929000),
 (200531, 'home_appliance', 1019000),
 (200532, 'home_appliance', 439000),
 (200533, 'home_appliance', 439000),
 (200534, 'home_appliance', 809000),
 (200535, 'home_appliance', 1059000),
 (200536, 'home_appliance', 2459000),
 (200537, 'home_appliance', 2459000),
 (200538, 'home_appliance', 2209000),
 (200539, 'home_appliance', 2209000),
 (200540, 'home_appliance', 2209000),
 (200541, 'home_appliance', 1899000),
 (200542, 'home_appliance', 1899000),
 (200543, 'home_appliance', 1899000),
 (200544, 'home_appliance', 2049000),
 (200545, 'home_appliance', 2049000),
 (200546, 'home_appliance', 2209000),
 (200547, 'home_appliance', 1385000),
 (200548, 'home_appliance', 1800000),
 (200549, 'home_appliance', 1909000),
 (200550, 'home_appliance', 434000),
 (200552, 'home_appliance', 1359000),
 (200554, 'home_appliance', 1409000),
 (200555, 'home_appliance', 1409000),
 (200556, 'home_appliance', 1359000),
 (200557, 'home_appliance', 1169000),
 (200558, 'home_appliance', 309000),
 (200559, 'home_appliance', 1800000),
 (200560, 'home_appliance', 1700000),
 (200561, 'home_appliance', 1900000),
 (200562, 'stuff', 39800),
 (200563, 'stuff', 49800),
 (200566, 'stuff', 29800),
 (200567, 'stuff', 49800),
 (200568, 'stuff', 59800),
 (200569, 'stuff', 39800),
 (200570, 'stuff', 49800),
 (200571, 'stuff', 49800),
 (200572, 'stuff', 59800),
 (200573, 'stuff', 39800),
 (200574, 'stuff', 49800),
 (200575, 'food', 33900),
 (200576, 'food', 30900),
 (200577, 'food', 40900),
 (200578, 'food', 30900),
 (200579, 'food', 38900),
 (200580, 'food', 40900),
 (200581, 'food', 52900),
 (200583, 'food', 54900),
 (200584, 'food', 55900),
 (200585, 'food', 55900),
 (200586, 'food', 60900),
 (200587, 'food', 60900),
 (200589, 'food', 38900),
 (200590, 'stuff', 169000),
 (200591, 'stuff', 219000),
 (200592, 'daily_supplies', 129000),
 (200593, 'daily_supplies', 109000),
 (200594, 'daily_supplies', 69800),
 (200595, 'daily_supplies', 119000),
 (200596, 'daily_supplies', 99000),
 (200597, 'daily_supplies', 88000),
 (200598, 'daily_supplies', 108000),
 (200599, 'daily_supplies', 159000),
 (200600, 'daily_supplies', 258000),
 (200601, 'daily_supplies', 99000),
 (200602, 'food', 59900),
 (200603, 'food', 49900),
 (200604, 'food', 39900),
 (200605, 'beauty', 69900),
 (200606, 'kitchen', 139000),
 (200607, 'kitchen', 56900),
 (200608, 'kitchen', 49000),
 (200609, 'kitchen', 129000),
 (200610, 'cloth', 69900),
 (200611, 'cloth', 49000),
 (200612, 'daily_supplies', 440000),
 (200613, 'daily_supplies', 490000),
 (200614, 'daily_supplies', 400000),
 (200615, 'daily_supplies', 450000),
 (200618, 'stuff', 188000),
 (200619, 'stuff', 239000),
 (200620, 'stuff', 48900),
 (200622, 'stuff', 249000),
 (200623, 'stuff', 259000),
 (200624, 'stuff', 138000),
 (200625, 'stuff', 269000),
 (200626, 'stuff', 199000),
 (200627, 'stuff', 199000),
 (200628, 'stuff', 219000),
 (200629, 'stuff', 138000),
 (200630, 'stuff', 238000),
 (200631, 'stuff', 198000),
 (200632, 'stuff', 198000),
 (200633, 'stuff', 229000),
 (200634, 'stuff', 148000),
 (200635, 'stuff', 259000),
 (200636, 'stuff', 238000),
 (200637, 'stuff', 238000),
 (200638, 'stuff', 238000),
 (200639, 'stuff', 239000),
 (200640, 'stuff', 138000),
 (200641, 'stuff', 199000),
 (200642, 'stuff', 229000),
 (200643, 'stuff', 249000),
 (200644, 'stuff', 238000),
 (200645, 'stuff', 169000),
 (200646, 'stuff', 159000),
 (200647, 'underwear', 89900),
 (200648, 'underwear', 69900),
 (200649, 'underwear', 59900),
 (200650, 'underwear', 39000),
 (200652, 'underwear', 69900),
 (200653, 'underwear', 59900),
 (200655, 'underwear', 39900),
 (200656, 'underwear', 49900),
 (200657, 'underwear', 49900),
 (200658, 'underwear', 69900),
 (200659, 'underwear', 49900),
 (200660, 'underwear', 59900),
 (200661, 'underwear', 89900),
 (200662, 'underwear', 59900),
 (200663, 'stuff', 29900),
 (200664, 'stuff', 29800),
 (200665, 'stuff', 29800),
 (200666, 'stuff', 29800),
 (200667, 'stuff', 29000),
 (200669, 'food', 51900),
 (200670, 'food', 50900),
 (200671, 'food', 50900),
 (200672, 'bedding', 179000),
 (200673, 'bedding', 159000),
 (200674, 'bedding', 139000),
 (200675, 'bedding', 129000),
 (200676, 'bedding', 149000),
 (200677, 'bedding', 169000),
 (200678, 'bedding', 109000),
 (200679, 'bedding', 139000),
 (200680, 'bedding', 129000),
 (200681, 'bedding', 159000),
 (200682, 'bedding', 149000),
 (200683, 'bedding', 179000),
 (200684, 'daily_supplies', 49800),
 (200685, 'food', 55900),
 (200686, 'furniture', 749000),
 (200687, 'furniture', 849000),
 (200690, 'furniture', 949000),
 (200691, 'furniture', 1049000),
 (200694, 'furniture', 1249000),
 (200695, 'furniture', 1349000),
 (200698, 'furniture', 1449000),
 (200699, 'furniture', 1249000),
 (200700, 'furniture', 649000),
 (200701, 'furniture', 699000),
 (200702, 'furniture', 749000),
 (200703, 'furniture', 699000),
 (200706, 'furniture', 799000),
 (200707, 'furniture', 899000),
 (200710, 'furniture', 999000),
 (200711, 'furniture', 1199000),
 (200714, 'furniture', 1299000),
 (200715, 'furniture', 1349000),
 (200716, 'furniture', 1149000),
 (200717, 'furniture', 589000),
 (200718, 'furniture', 639000),
 (200719, 'furniture', 689000),
 (200720, 'furniture', 350000),
 (200721, 'furniture', 849000),
 (200731, 'furniture', 648000),
 (200732, 'furniture', 598000),
 (200733, 'furniture', 548000),
 (200734, 'furniture', 548000),
 (200735, 'furniture', 548000),
 (200736, 'furniture', 598000),
 (200737, 'furniture', 598000),
 (200738, 'furniture', 648000),
 (200739, 'furniture', 648000),
 (200740, 'furniture', 199000),
 (200741, 'furniture', 139000),
 (200742, 'furniture', 169000),
 (200744, 'daily_supplies', 40900),
 (200745, 'kitchen', 89000),
 (200746, 'kitchen', 129000),
 (200747, 'kitchen', 188000),
 (200748, 'kitchen', 239000),
 (200749, 'daily_supplies', 50900),
 (200750, 'kitchen', 79000),
 (200751, 'kitchen', 119000),
 (200752, 'kitchen', 168000),
 (200753, 'kitchen', 229000),
 (200754, 'beauty', 49900),
 (200755, 'beauty', 39900),
 (200756, 'beauty', 49900),
 (200757, 'beauty', 39900),
 (200758, 'beauty', 59900),
 (200759, 'beauty', 39900),
 (200760, 'cloth', 49000),
 (200761, 'stuff', 129000),
 (200762, 'kitchen', 74900),
 (200763, 'daily_supplies', 29800),
 (200764, 'daily_supplies', 39800),
 (200765, 'daily_supplies', 59800),
 (200766, 'stuff', 159000),
 (200767, 'stuff', 59000),
 (200768, 'stuff', 139000),
 (200769, 'stuff', 149000),
 (200770, 'health', 99000),
 (200771, 'cloth', 49000),
 (200772, 'cloth', 49000),
 (200773, 'cloth', 79000),
 (200774, 'cloth', 79000),
 (200776, 'underwear', 89000),
 (200777, 'underwear', 89000),
 (200778, 'underwear', 89000),
 (200779, 'underwear', 89000),
 (200780, 'underwear', 89000),
 (200781, 'underwear', 89000),

In [21]:
%%sql

select RANK() OVER(order by category) FROM item_data;

 * postgresql://postgres:***@localhost:5432/postgres
2042 rows affected.

[(1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (1,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (65,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (125,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (487,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (670,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (822,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (936,),
 (992,),
 (992,),
 (992,),
 (992,),
 (992,),
 (992,),
 (992,),
 (992,),
 (992,),
 ...]

In [84]:
%%sql
SELECT
category,
STRING_AGG(RIGHT(itemcode::varchar,2), ORDER BY price) itemcodes
FROM item_data
group by 1
LIMIT 10;

 * postgresql://postgres:***@localhost:5432/postgres
(psycopg2.errors.SyntaxError) 오류:  구문 오류, "ORDER" 부근
LINE 3: STRING_AGG(RIGHT(itemcode::varchar,2), ORDER BY price) itemc...
                                               ^

[SQL: SELECT
category,
STRING_AGG(RIGHT(itemcode::varchar,2), ORDER BY price) itemcodes
FROM item_data
group by 1
LIMIT 10;]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [58]:
%%sql
SELECT
DISTINCT
category,
STRING_AGG(RiGHT(itemcode::varchar,2),' ') OVER(partition by category order by price rows between unbounded preceding and unbounded following) itemcodes
FROM item_data
LIMIT 10;

 * postgresql://postgres:***@localhost:5432/postgres
10 rows affected.

[('stuff', '32 31 29 28 67 91 56 86 55 66 65 30 27 26 64 39 66 89 63 41 32 40 30 27 04 15 83 60 42 40 37 35 33 31 62 69 73 47 63 92 90 88 87 45 84 93 89 54 91 62 ... (628 characters truncated) ... 00 02 01 32 94 02 09 09 97 24 71 36 89 90 03 41 13 42 88 87 81 80 85 86 84 25 26 82 52 16 38 03 91 99 43 10 44 07 37 33 70 69 01 08 39 40 35 28 29 30'),
 ('home_appliance', '72 20 67 58 91 33 15 25 32 24 50 33 32 83 36 27 65 64 28 69 69 34 35 70 71 72 70 61 63 62 64 18 26 27 68 17 16 76 73 74 75 67 68 66 65 39 66 31 38 75 ... (478 characters truncated) ... 22 21 20 17 37 36 23 19 81 64 68 50 69 53 48 65 12 78 54 53 50 55 47 46 45 25 23 18 16 15 13 28 95 52 24 13 93 92 91 26 27 51 48 49 57 60 10 56 58 59'),
 ('daily_supplies', '52 62 01 63 99 00 92 72 36 72 30 51 65 54 09 64 47 92 61 73 28 84 86 45 87 44 19 36 03 27 37 40 11 01 89 19 84 08 44 21 12 02 20 49 88 22 50 00 31 71 ... (250 characters truncated) ... 45 67 53 64 75 83 14 19 78 86 73 69 52 96 80 18 61 60 68 16 82 22 65 39 00 38 40 41 25 79 80 76 81 74 85 26 31 30 27 14 17 12 15 15 13 26 07 67 66 06'),
 ('underwear', '89 74 50 88 55 76 12 09 08 42 07 10 09 12 13 39 79 70 67 68 22 13 57 04 05 06 90 13 59 72 20 56 32 14 54 46 47 48 49 50 51 53 54 59 20 17 51 74 75 37 ... (415 characters truncated) ... 05 06 47 57 11 08 20 19 03 80 58 36 55 59 60 09 02 56 15 16 98 87 99 76 70 69 85 54 80 78 75 71 92 52 81 82 77 76 71 57 72 58 79 98 55 56 90 53 73 57'),
 ('beauty', '00 01 02 08 07 97 99 62 38 63 59 55 57 12 81 82 72 80 60 93 74 56 54 14 26 61 83 30 31 32 96 01 14 39 64 65 76 97 58 29 28 55 81 28 00 13 34 79 23 70 79 24 22 20 19 40 23 05 49 61 80 03 00 15'),
 ('food', '50 55 33 34 35 24 26 07 64 63 64 62 78 76 76 13 12 25 89 60 91 84 52 75 00 90 90 73 89 79 31 30 69 46 01 88 06 04 13 50 49 63 62 25 73 46 14 70 65 80 ... (157 characters truncated) ... 25 23 18 17 03 02 70 71 69 64 81 83 85 85 84 14 18 13 96 85 83 65 66 71 69 67 02 38 44 45 47 49 10 05 05 99 98 97 87 86 12 89 09 33 48 87 75 11 76 33'),
 ('health', '59 06 77 35 34 15 39 27 25 92 55 29 05 91 42 21 02 10 20 72 80 79 78 08 09 23 33 85 82 77 76 75 74 34 44 19 81 26 06 70 22 12 98 95 48 41 40 45 93 57 38 13 37 64 24 49'),
 ('bedding', '88 05 01 74 84 89 09 75 73 77 82 85 93 08 07 97 99 05 98 06 86 95 76 98 10 91 03 72 83 90 00 02 87 75 94 00 96 92 04 78 99 80 75 79 74 82 76 73 81 41 77 24 83 72 39 22 42 25 40 23'),
 ('kitchen', '68 21 04 34 18 83 22 07 06 05 34 35 55 54 91 33 69 51 08 53 52 86 32 85 50 35 19 33 18 49 07 74 50 84 46 61 38 37 36 48 88 15 87 60 45 79 85 48 17 58 ... (436 characters truncated) ... 47 79 58 77 70 69 68 80 78 37 56 33 45 34 66 55 67 29 65 27 85 28 82 38 06 53 75 30 04 48 12 62 54 81 87 11 74 49 61 35 36 32 31 66 65 76 63 77 64 11'),
 ('furniture', '93 41 42 40 06 20 03 11 10 33 34 35 05 04 09 12 17 36 37 32 08 06 19 13 03 07 18 38 39 31 20 45 07 21 02 00 19 22 01 03 23 24 86 28 02 06 07 87 21 07 ... (43 characters truncated) ... 29 11 94 99 90 91 14 52 97 94 15 95 43 05 47 98 35 92 89 30 26 93 44 88 27 49 66 32 50 33 09 11 08 62 53 10 65 56 54 63 21 57 64 55 38 60 58 36 59 37')]

In [85]:
%%sql

SELECT * FROM order_data LIMIT 10;

 * postgresql://postgres:***@localhost:5432/postgres
10 rows affected.

[(0, datetime.date(2019, 1, 1), 200197, 222836000),
 (1, datetime.date(2019, 1, 1), 200896, 115831000),
 (2, datetime.date(2019, 1, 1), 201072, 12033000),
 (3, datetime.date(2019, 1, 1), 201079, 20663000),
 (4, datetime.date(2019, 1, 1), 201220, 51795000),
 (5, datetime.date(2019, 1, 1), 201226, 68135000),
 (6, datetime.date(2019, 1, 1), 202044, 154715000),
 (7, datetime.date(2019, 1, 1), 202377, 99736000),
 (8, datetime.date(2019, 1, 1), 202395, 259678000),
 (9, datetime.date(2019, 1, 1), 202404, 90973000)]

In [90]:
%%sql
SELECT order_id, date, itemcode, LAG(itemcode,1) OVER(PARTITION BY date ORDER BY order_id) AS prev_itemcode
FROM
order_data
order by prev_itemcode DESC,date;

 * postgresql://postgres:***@localhost:5432/postgres
12738 rows affected.

[(0, datetime.date(2019, 1, 1), 200197, None),
 (22, datetime.date(2019, 1, 2), 200896, None),
 (58, datetime.date(2019, 1, 3), 200197, None),
 (91, datetime.date(2019, 1, 4), 200197, None),
 (120, datetime.date(2019, 1, 5), 200756, None),
 (154, datetime.date(2019, 1, 6), 200197, None),
 (182, datetime.date(2019, 1, 7), 200197, None),
 (212, datetime.date(2019, 1, 8), 200883, None),
 (246, datetime.date(2019, 1, 9), 202261, None),
 (274, datetime.date(2019, 1, 10), 200197, None),
 (306, datetime.date(2019, 1, 11), 200881, None),
 (336, datetime.date(2019, 1, 12), 200197, None),
 (372, datetime.date(2019, 1, 13), 200197, None),
 (403, datetime.date(2019, 1, 14), 201457, None),
 (434, datetime.date(2019, 1, 15), 201059, None),
 (472, datetime.date(2019, 1, 16), 200197, None),
 (502, datetime.date(2019, 1, 17), 200197, None),
 (531, datetime.date(2019, 1, 18), 201059, None),
 (557, datetime.date(2019, 1, 19), 201794, None),
 (595, datetime.date(2019, 1, 20), 200197, None),
 (636, datetime.date(2019, 1, 21), 200756, None),
 (666, datetime.date(2019, 1, 22), 200197, None),
 (704, datetime.date(2019, 1, 23), 200197, None),
 (735, datetime.date(2019, 1, 24), 201161, None),
 (766, datetime.date(2019, 1, 25), 202403, None),
 (798, datetime.date(2019, 1, 26), 200197, None),
 (820, datetime.date(2019, 1, 27), 200197, None),
 (857, datetime.date(2019, 1, 28), 201414, None),
 (882, datetime.date(2019, 1, 29), 200197, None),
 (908, datetime.date(2019, 1, 30), 201059, None),
 (947, datetime.date(2019, 1, 31), 200197, None),
 (973, datetime.date(2019, 2, 1), 200197, None),
 (1002, datetime.date(2019, 2, 2), 200197, None),
 (1039, datetime.date(2019, 2, 3), 200197, None),
 (1072, datetime.date(2019, 2, 4), 200197, None),
 (1098, datetime.date(2019, 2, 5), 200197, None),
 (1133, datetime.date(2019, 2, 6), 200197, None),
 (1173, datetime.date(2019, 2, 7), 200197, None),
 (1205, datetime.date(2019, 2, 8), 200197, None),
 (1242, datetime.date(2019, 2, 9), 200896, None),
 (1275, datetime.date(2019, 2, 10), 200197, None),
 (1310, datetime.date(2019, 2, 11), 200844, None),
 (1331, datetime.date(2019, 2, 12), 200197, None),
 (1369, datetime.date(2019, 2, 13), 200197, None),
 (1402, datetime.date(2019, 2, 14), 200197, None),
 (1436, datetime.date(2019, 2, 15), 200844, None),
 (1473, datetime.date(2019, 2, 16), 200197, None),
 (1506, datetime.date(2019, 2, 17), 200197, None),
 (1539, datetime.date(2019, 2, 18), 200197, None),
 (1574, datetime.date(2019, 2, 19), 200197, None),
 (1615, datetime.date(2019, 2, 20), 200197, None),
 (1652, datetime.date(2019, 2, 21), 202261, None),
 (1690, datetime.date(2019, 2, 22), 201047, None),
 (1720, datetime.date(2019, 2, 23), 200197, None),
 (1749, datetime.date(2019, 2, 24), 200197, None),
 (1789, datetime.date(2019, 2, 25), 200197, None),
 (1817, datetime.date(2019, 2, 26), 201414, None),
 (1843, datetime.date(2019, 2, 27), 200197, None),
 (1873, datetime.date(2019, 2, 28), 201414, None),
 (1909, datetime.date(2019, 3, 1), 200197, None),
 (1946, datetime.date(2019, 3, 2), 200197, None),
 (1986, datetime.date(2019, 3, 3), 201370, None),
 (2027, datetime.date(2019, 3, 4), 201412, None),
 (2062, datetime.date(2019, 3, 5), 200197, None),
 (2104, datetime.date(2019, 3, 6), 200760, None),
 (2140, datetime.date(2019, 3, 7), 201221, None),
 (2171, datetime.date(2019, 3, 8), 202294, None),
 (2207, datetime.date(2019, 3, 9), 201047, None),
 (2239, datetime.date(2019, 3, 10), 200197, None),
 (2276, datetime.date(2019, 3, 11), 200197, None),
 (2307, datetime.date(2019, 3, 12), 200889, None),
 (2341, datetime.date(2019, 3, 13), 200242, None),
 (2382, datetime.date(2019, 3, 14), 200243, None),
 (2416, datetime.date(2019, 3, 15), 200889, None),
 (2451, datetime.date(2019, 3, 16), 200243, None),
 (2480, datetime.date(2019, 3, 17), 200243, None),
 (2516, datetime.date(2019, 3, 18), 201223, None),
 (2548, datetime.date(2019, 3, 19), 200243, None),
 (2585, datetime.date(2019, 3, 20), 200197, None),
 (2618, datetime.date(2019, 3, 21), 200197, None),
 (2655, datetime.date(2019, 3, 22), 200755, None),
 (2692, datetime.date(2019, 3, 23), 200243, None),
 (2731, datetime.date(2019, 3, 24), 200197, None),
 (2775, datetime.date(2019, 3, 25), 200200, None),
 (2812, datetime.date(2019, 3, 26), 200200, None),
 (2844, datetime.date(2019, 3, 27), 200837, None),
 (2878, datetime.date(2019, 3, 28), 200242, None),
 (2913, datetime.date(2019, 3, 29), 200200, None),
 (2952, datetime.date(2019, 3, 30), 200755, None),
 (2994, datetime.date(2019, 3, 31), 200200, None),
 (3043, datetime.date(2019, 4, 1), 200755, None),
 (3086, datetime.date(2019, 4, 2), 201008, None),
 (3128, datetime.date(2019, 4, 3), 201222, None),
 (3172, datetime.date(2019, 4, 4), 200879, None),
 (3210, datetime.date(2019, 4, 5), 201432, None),
 (3255, datetime.date(2019, 4, 6), 201008, None),
 (3296, datetime.date(2019, 4, 7), 200341, None),
 (3344, datetime.date(2019, 4, 8), 200200, None),
 (3391, datetime.date(2019, 4, 9), 200200, None),
 (3419, datetime.date(2019, 4, 10), 200845, None),
 (3461, datetime.date(2019, 4, 11), 200758, None),
 (3497, datetime.date(2019, 4, 12), 200200, None),
 (3542, datetime.date(2019, 4, 13), 200845, None),
 (3579, datetime.date(2019, 4, 14), 200200, None),
 (3623, datetime.date(2019, 4, 15), 200200, None),
 (3664, datetime.date(2019, 4, 16), 200845, None),
 (3699, datetime.date(2019, 4, 17), 201149, None),
 (3744, datetime.date(2019, 4, 18), 200200, None),
 (3785, datetime.date(2019, 4, 19), 202028, None),
 (3828, datetime.date(2019, 4, 20), 200200, None),
 (3855, datetime.date(2019, 4, 21), 200200, None),
 (3895, datetime.date(2019, 4, 22), 200344, None),
 (3925, datetime.date(2019, 4, 23), 200375, None),
 (3964, datetime.date(2019, 4, 24), 200200, None),
 (4002, datetime.date(2019, 4, 25), 201669, None),
 (4046, datetime.date(2019, 4, 26), 202264, None),
 (4083, datetime.date(2019, 4, 27), 200200, None),
 (4115, datetime.date(2019, 4, 28), 200200, None),
 (4150, datetime.date(2019, 4, 29), 200344, None),
 (4183, datetime.date(2019, 4, 30), 201394, None),
 (4213, datetime.date(2019, 5, 1), 200200, None),
 (4253, datetime.date(2019, 5, 2), 201669, None),
 (4288, datetime.date(2019, 5, 3), 200675, None),
 (4334, datetime.date(2019, 5, 4), 200200, None),
 (4373, datetime.date(2019, 5, 5), 200200, None),
 (4419, datetime.date(2019, 5, 6), 200200, None),
 (4461, datetime.date(2019, 5, 7), 200344, None),
 (4498, datetime.date(2019, 5, 8), 200375, None),
 (4541, datetime.date(2019, 5, 9), 200241, None),
 (4580, datetime.date(2019, 5, 10), 200241, None),
 (4625, datetime.date(2019, 5, 11), 200200, None),
 (4671, datetime.date(2019, 5, 12), 200200, None),
 (4719, datetime.date(2019, 5, 13), 200241, None),
 (4766, datetime.date(2019, 5, 14), 202264, None),
 (4813, datetime.date(2019, 5, 15), 200200, None),
 (4849, datetime.date(2019, 5, 16), 200241, None),
 (4888, datetime.date(2019, 5, 17), 200200, None),
 (4915, datetime.date(2019, 5, 18), 200200, None),
 (4951, datetime.date(2019, 5, 19), 200200, None),
 (4987, datetime.date(2019, 5, 20), 201132, None),
 (5031, datetime.date(2019, 5, 21), 200200, None),
 (5072, datetime.date(2019, 5, 22), 200754, None),
 (5104, datetime.date(2019, 5, 23), 200200, None),
 (5140, datetime.date(2019, 5, 24), 200200, None),
 (5172, datetime.date(2019, 5, 25), 200342, None),
 (5212, datetime.date(2019, 5, 26), 200200, None),
 (5245, datetime.date(2019, 5, 27), 200200, None),
 (5279, datetime.date(2019, 5, 28), 200372, None),
 (5304, datetime.date(2019, 5, 29), 200754, None),
 (5340, datetime.date(2019, 5, 30), 200757, None),
 (5368, datetime.date(2019, 5, 31), 201420, None),
 (5398, datetime.date(2019, 6, 1), 200200, None),
 (5429, datetime.date(2019, 6, 2), 200200, None),
 (5467, datetime.date(2019, 6, 3), 200372, None),
 (5505, datetime.date(2019, 6, 4), 200372, None),
 (5537, datetime.date(2019, 6, 5), 200675, None),
 (5571, datetime.date(2019, 6, 6), 200342, None),
 (5611, datetime.date(2019, 6, 7), 200372, None),
 (5652, datetime.date(2019, 6, 8), 200202, None),
 (5680, datetime.date(2019, 6, 9), 200202, None),
 (5719, datetime.date(2019, 6, 10), 200372, None),
 (5752, datetime.date(2019, 6, 11), 200202, None),
 (5794, datetime.date(2019, 6, 12), 201297, None),
 (5829, datetime.date(2019, 6, 13), 201232, None),
 (5858, datetime.date(2019, 6, 14), 200372, None),
 (5892, datetime.date(2019, 6, 15), 200342, None),
 (5936, datetime.date(2019, 6, 16), 200372, None),
 (5966, datetime.date(2019, 6, 17), 201934, None),
 (6007, datetime.date(2019, 6, 18), 200202, None),
 (6033, datetime.date(2019, 6, 19), 201297, None),
 (6070, datetime.date(2019, 6, 20), 200372, None),
 (6106, datetime.date(2019, 6, 21), 201297, None),
 (6132, datetime.date(2019, 6, 22), 202260, None),
 (6160, datetime.date(2019, 6, 23), 201297, None),
 (6200, datetime.date(2019, 6, 24), 200202, None),
 (6228, datetime.date(2019, 6, 25), 200202, None),
 (6252, datetime.date(2019, 6, 26), 200372, None),
 (6285, datetime.date(2019, 6, 27), 201297, None),
 (6313, datetime.date(2019, 6, 28), 201934, None),
 (6343, datetime.date(2019, 6, 29), 200202, None),
 (6381, datetime.date(2019, 6, 30), 200390, None),
 (6415, datetime.date(2019, 7, 1), 200202, None),
 (6453, datetime.date(2019, 7, 2), 202260, None),
 (6490, datetime.date(2019, 7, 3), 200202, None),
 (6527, datetime.date(2019, 7, 4), 200390, None),
 (6559, datetime.date(2019, 7, 5), 200202, None),
 (6592, datetime.date(2019, 7, 6), 202260, None),
 (6624, datetime.date(2019, 7, 7), 200201, None),
 (6662, datetime.date(2019, 7, 8), 201297, None),
 (6704, datetime.date(2019, 7, 9), 200115, None),
 (6745, datetime.date(2019, 7, 10), 200201, None),
 (6778, datetime.date(2019, 7, 11), 200390, None),
 (6820, datetime.date(2019, 7, 12), 200201, None),
 (6852, datetime.date(2019, 7, 13), 201375, None),
 (6885, datetime.date(2019, 7, 14), 200372, None),
 (6933, datetime.date(2019, 7, 15), 200201, None),
 (6976, datetime.date(2019, 7, 16), 202263, None),
 (7008, datetime.date(2019, 7, 17), 200390, None),
 (7053, datetime.date(2019, 7, 18), 201375, None),
 (7087, datetime.date(2019, 7, 19), 200201, None),
 (7126, datetime.date(2019, 7, 20), 202263, None),
 (7173, datetime.date(2019, 7, 21), 200201, None),
 (7212, datetime.date(2019, 7, 22), 201297, None),
 (7252, datetime.date(2019, 7, 23), 202239, None),
 (7293, datetime.date(2019, 7, 24), 200201, None),
 (7335, datetime.date(2019, 7, 25), 200890, None),
 (7370, datetime.date(2019, 7, 26), 202260, None),
 (7401, datetime.date(2019, 7, 27), 202239, None),
 (7439, datetime.date(2019, 7, 28), 200201, None),
 (7477, datetime.date(2019, 7, 29), 200201, None),
 (7506, datetime.date(2019, 7, 30), 200759, None),
 (7545, datetime.date(2019, 7, 31), 202239, None),
 (7576, datetime.date(2019, 8, 1), 200302, None),
 (7615, datetime.date(2019, 8, 2), 200759, None),
 (7647, datetime.date(2019, 8, 3), 201287, None),
 (7679, datetime.date(2019, 8, 4), 202239, None),
 (7725, datetime.date(2019, 8, 5), 202263, None),
 (7765, datetime.date(2019, 8, 6), 202239, None),
 (7794, datetime.date(2019, 8, 7), 201375, None),
 (7842, datetime.date(2019, 8, 8), 200201, None),
 (7871, datetime.date(2019, 8, 9), 201144, None),
 (7910, datetime.date(2019, 8, 10), 200201, None),
 (7942, datetime.date(2019, 8, 11), 200823, None),
 (7983, datetime.date(2019, 8, 12), 201144, None),
 (8026, datetime.date(2019, 8, 13), 200759, None),
 (8058, datetime.date(2019, 8, 14), 200201, None),
 (8100, datetime.date(2019, 8, 15), 200910, None),
 (8142, datetime.date(2019, 8, 16), 201296, None),
 (8180, datetime.date(2019, 8, 17), 201144, None),
 (8213, datetime.date(2019, 8, 18), 201315, None),
 (8247, datetime.date(2019, 8, 19), 200201, None),
 (8286, datetime.date(2019, 8, 20), 202239, None),
 (8323, datetime.date(2019, 8, 21), 200759, None),
 (8352, datetime.date(2019, 8, 22), 202239, None),
 (8390, datetime.date(2019, 8, 23), 200256, None),
 (8423, datetime.date(2019, 8, 24), 201396, None),
 (8438, datetime.date(2019, 8, 25), 202239, None),
 (8472, datetime.date(2019, 8, 26), 200000, None),
 (8504, datetime.date(2019, 8, 27), 200201, None),
 (8531, datetime.date(2019, 8, 28), 202239, None),
 (8558, datetime.date(2019, 8, 29), 201296, None),
 (8583, datetime.date(2019, 8, 30), 200000, None),
 (8608, datetime.date(2019, 8, 31), 200823, None),
 (8642, datetime.date(2019, 9, 1), 200199, None),
 (8680, datetime.date(2019, 9, 2), 202239, None),
 (8714, datetime.date(2019, 9, 3), 200123, None),
 (8743, datetime.date(2019, 9, 4), 201032, None),
 (8776, datetime.date(2019, 9, 5), 202080, None),
 (8811, datetime.date(2019, 9, 6), 201519, None),
 (8849, datetime.date(2019, 9, 7), 200199, None),
 (8881, datetime.date(2019, 9, 8), 200383, None),
 (8910, datetime.date(2019, 9, 9), 200199, None),
 (8935, datetime.date(2019, 9, 10), 200882, None),
 (8976, datetime.date(2019, 9, 11), 200872, None),
 (9011, datetime.date(2019, 9, 12), 200199, None),
 (9042, datetime.date(2019, 9, 13), 201040, None),
 (9080, datetime.date(2019, 9, 14), 200882, None),
 (9116, datetime.date(2019, 9, 15), 201040, None),
 (9148, datetime.date(2019, 9, 16), 200882, None),
 (9188, datetime.date(2019, 9, 17), 200199, None),
 (9233, datetime.date(2019, 9, 18), 200398, None),
 (9278, datetime.date(2019, 9, 19), 202239, None),
 (9309, datetime.date(2019, 9, 20), 202262, None),
 (9346, datetime.date(2019, 9, 21), 200199, None),
 (9381, datetime.date(2019, 9, 22), 201213, None),
 (9436, datetime.date(2019, 9, 23), 201007, None),
 (9470, datetime.date(2019, 9, 24), 202239, None),
 (9505, datetime.date(2019, 9, 25), 200823, None),
 (9524, datetime.date(2019, 9, 26), 200882, None),
 (9554, datetime.date(2019, 9, 27), 201012, None),
 (9583, datetime.date(2019, 9, 28), 201007, None),
 (9621, datetime.date(2019, 9, 29), 201007, None),
 (9650, datetime.date(2019, 9, 30), 200874, None),
 (9685, datetime.date(2019, 10, 1), 201007, None),
 (9722, datetime.date(2019, 10, 2), 200199, None),
 (9756, datetime.date(2019, 10, 3), 200824, None),
 (9801, datetime.date(2019, 10, 4), 200882, None),
 (9838, datetime.date(2019, 10, 5), 200823, None),
 (9875, datetime.date(2019, 10, 6), 200828, None),
 (9918, datetime.date(2019, 10, 7), 200382, None),
 (9951, datetime.date(2019, 10, 8), 200199, None),
 (9988, datetime.date(2019, 10, 9), 200830, None),
 (10033, datetime.date(2019, 10, 10), 200199, None),
 (10066, datetime.date(2019, 10, 11), 201007, None),
 (10095, datetime.date(2019, 10, 12), 202038, None),
 (10133, datetime.date(2019, 10, 13), 201032, None),
 (10159, datetime.date(2019, 10, 14), 200828, None),
 (10193, datetime.date(2019, 10, 15), 201012, None),
 (10229, datetime.date(2019, 10, 16), 200882, None),
 (10261, datetime.date(2019, 10, 17), 201040, None),
 (10291, datetime.date(2019, 10, 18), 201012, None),
 (10329, datetime.date(2019, 10, 19), 201007, None),
 (10363, datetime.date(2019, 10, 20), 200823, None),
 (10398, datetime.date(2019, 10, 21), 201013, None),
 (10428, datetime.date(2019, 10, 22), 201012, None),
 (10463, datetime.date(2019, 10, 23), 200823, None),
 (10493, datetime.date(2019, 10, 24), 200305, None),
 (10531, datetime.date(2019, 10, 25), 200828, None),
 (10555, datetime.date(2019, 10, 26), 201057, None),
 (10581, datetime.date(2019, 10, 27), 201007, None),
 (10610, datetime.date(2019, 10, 28), 202398, None),
 (10636, datetime.date(2019, 10, 29), 200823, None),
 (10674, datetime.date(2019, 10, 30), 201007, None),
 (10701, datetime.date(2019, 10, 31), 201012, None),
 (10735, datetime.date(2019, 11, 1), 200605, None),
 (10765, datetime.date(2019, 11, 2), 200199, None),
 (10794, datetime.date(2019, 11, 3), 201032, None),
 (10830, datetime.date(2019, 11, 4), 200199, None),
 (10865, datetime.date(2019, 11, 5), 200319, None),
 (10897, datetime.date(2019, 11, 6), 200402, None),
 (10931, datetime.date(2019, 11, 7), 201040, None),
 (10971, datetime.date(2019, 11, 8), 201032, None),
 (11005, datetime.date(2019, 11, 9), 200320, None),
 (11033, datetime.date(2019, 11, 10), 200199, None),
 (11064, datetime.date(2019, 11, 11), 200823, None),
 (11100, datetime.date(2019, 11, 12), 200320, None),
 (11130, datetime.date(2019, 11, 13), 202239, None),
 (11164, datetime.date(2019, 11, 14), 200199, None),
 (11203, datetime.date(2019, 11, 15), 200828, None),
 (11227, datetime.date(2019, 11, 16), 201032, None),
 (11266, datetime.date(2019, 11, 17), 200199, None),
 (11293, datetime.date(2019, 11, 18), 201032, None),
 (11324, datetime.date(2019, 11, 19), 200394, None),
 (11361, datetime.date(2019, 11, 20), 200199, None),
 (11397, datetime.date(2019, 11, 21), 200320, None),
 (11434, datetime.date(2019, 11, 22), 200829, None),
 (11467, datetime.date(2019, 11, 23), 200199, None),
 (11487, datetime.date(2019, 11, 24), 201031, None),
 (11514, datetime.date(2019, 11, 25), 200199, None),
 (11545, datetime.date(2019, 11, 26), 200199, None),
 (11570, datetime.date(2019, 11, 27), 201031, None),
 (11601, datetime.date(2019, 11, 28), 200199, None),
 (11628, datetime.date(2019, 11, 29), 202239, None),
 (11663, datetime.date(2019, 11, 30), 200199, None),
 (11696, datetime.date(2019, 12, 1), 200199, None),
 (11733, datetime.date(2019, 12, 2), 201031, None),
 (11772, datetime.date(2019, 12, 3), 202239, None),
 (11813, datetime.date(2019, 12, 4), 200199, None),
 (11850, datetime.date(2019, 12, 5), 200828, None),
 (11881, datetime.date(2019, 12, 6), 200199, None),
 (11912, datetime.date(2019, 12, 7), 200876, None),
 (11943, datetime.date(2019, 12, 8), 200199, None),
 (11986, datetime.date(2019, 12, 9), 200320, None),
 (12031, datetime.date(2019, 12, 10), 200199, None),
 (12071, datetime.date(2019, 12, 11), 201040, None),
 (12106, datetime.date(2019, 12, 12), 200199, None),
 (12134, datetime.date(2019, 12, 13), 200828, None),
 (12166, datetime.date(2019, 12, 14), 200199, None),
 (12203, datetime.date(2019, 12, 15), 200199, None),
 (12236, datetime.date(2019, 12, 16), 201030, None),
 (12274, datetime.date(2019, 12, 17), 201030, None),
 (12312, datetime.date(2019, 12, 18), 201007, None),
 (12343, datetime.date(2019, 12, 19), 200828, None),
 (12377, datetime.date(2019, 12, 20), 201007, None),
 (12406, datetime.date(2019, 12, 21), 201030, None),
 (12433, datetime.date(2019, 12, 22), 201007, None),
 (12456, datetime.date(2019, 12, 23), 200828, None),
 (12491, datetime.date(2019, 12, 24), 200199, None),
 (12533, datetime.date(2019, 12, 25), 200876, None),
 (12567, datetime.date(2019, 12, 26), 200828, None),
 (12591, datetime.date(2019, 12, 27), 200199, None),
 (12616, datetime.date(2019, 12, 28), 200876, None),
 (12648, datetime.date(2019, 12, 29), 201030, None),
 (12673, datetime.date(2019, 12, 30), 200199, None),
 (12698, datetime.date(2019, 12, 31), 200885, None),
 (12734, datetime.date(2020, 1, 1), 201383, None),
 (10304, datetime.date(2019, 10, 18), 200686, 202513),
 (10507, datetime.date(2019, 10, 24), 201820, 202513),
 (10621, datetime.date(2019, 10, 28), 201655, 202513),
 (10778, datetime.date(2019, 11, 2), 201927, 202513),
 (10817, datetime.date(2019, 11, 3), 200248, 202513),
 (10911, datetime.date(2019, 11, 6), 200735, 202513),
 (11020, datetime.date(2019, 11, 9), 200248, 202513),
 (11113, datetime.date(2019, 11, 12), 201820, 202513),
 (11175, datetime.date(2019, 11, 14), 200145, 202513),
 (11871, datetime.date(2019, 12, 5), 201620, 202513),
 (12089, datetime.date(2019, 12, 11), 200734, 202513),
 (12185, datetime.date(2019, 12, 14), 200489, 202513),
 (12388, datetime.date(2019, 12, 20), 201188, 202513),
 (14, datetime.date(2019, 1, 1), 200465, 202512),
 (132, datetime.date(2019, 1, 5), 200432, 202512),
 (194, datetime.date(2019, 1, 7), 200465, 202512),
 (224, datetime.date(2019, 1, 8), 200432, 202512),
 (257, datetime.date(2019, 1, 9), 201002, 202512),
 (287, datetime.date(2019, 1, 10), 201002, 202512),
 (318, datetime.date(2019, 1, 11), 200487, 202512),
 (413, datetime.date(2019, 1, 14), 201234, 202512),
 (444, datetime.date(2019, 1, 15), 201002, 202512),
 (485, datetime.date(2019, 1, 16), 200465, 202512),
 (569, datetime.date(2019, 1, 19), 200432, 202512),